version: '3.7'

services:
  openvpn:
    image: lawtancool/docker-openvpn-xor@sha256:5c4169cb95e63b73c661c5e31dd7e85e55a7083f246953011864e817f3481846
    restart: unless-stopped
    volumes:
      - "./resolv.conf:/etc/netns/route/resolv.conf"
      - "./vpn:/etc/openvpn:ro"
      - "./scripts:/opt/scripts:ro"
      - "./rr:/var/rr:rw"
    pid: "service:route"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    command: ["/opt/scripts/ovpn-run.sh", "--up-restart"]
  route:
    build: build/iptables
    restart: unless-stopped
    init: true
    stop_signal: SIGKILL
    volumes:
      - "./resolv.conf:/etc/resolv.conf"
    cap_add:
      - NET_ADMIN
    networks:
      - bridge
    sysctls:
      - "net.ipv4.ping_group_range=0 2147483647"
      - "net.ipv4.ip_forward=1"
    command: ["sh", "-c", "iptables -t nat -A POSTROUTING -j MASQUERADE &&
                           iptables -A FORWARD -j ACCEPT &&
                           iptables -A OUTPUT -m owner --uid-owner 17818 -o eth0 -j REJECT &&
                           iptables -t mangle -A FORWARD -j TTL --ttl-inc 1 &&
                           ip route delete default && exec tail -f /dev/null"]
  dnsmasq:
    build: build/dnsmasq
    restart: unless-stopped
    stop_signal: SIGKILL
    network_mode: "service:route"
    command: --no-hosts --cache-size=0 --strict-order --clear-on-reload
  socks5:
    image: ghcr.io/wzshiming/socks5/socks5:v0.4.3@sha256:4e0522e32c7d20cc4e498ff2e5d9f43ed4bb5fe1de287e7122a1feafbcdec1f7
    restart: unless-stopped
    network_mode: "service:route"
    user: "17818"
  socat2unix:
    image: alpine/socat:1.7.4.4@sha256:93efcf633c5489b170404df25e289f811cabeea728a5367f0c9b1560982edf14
    restart: unless-stopped
    volumes:
      - "./sock:/var/sock:rw"
    network_mode: "service:route"
    command: ["unix-listen:/var/sock/socks5,fork,unlink-early", "tcp-connect:127.0.0.1:1080"]
  socat2port:
    image: alpine/socat:1.7.4.4@sha256:93efcf633c5489b170404df25e289f811cabeea728a5367f0c9b1560982edf14
    restart: unless-stopped
    volumes:
      - "./sock:/var/sock:ro"
    ports:
      - "1080:1080"
    command: ["tcp-listen:1080,fork", "unix-connect:/var/sock/socks5"]
networks:
  bridge:
    internal: false
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
