version: '3.7'

services:
  wireguard:
    build: build/wireguard
    restart: unless-stopped
    volumes:
      - "./resolv.conf:/etc/netns/route/resolv.conf"
      - "./wireguard:/etc/wireguard:ro"
      - "./scripts:/opt/scripts:ro"
    pid: "service:route"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    command: ["/opt/scripts/wg-run.sh"]
  route:
    image: busybox
    restart: unless-stopped
    init: true
    stop_signal: SIGKILL
    volumes:
      - "./resolv.conf:/etc/resolv.conf"
    network_mode: none
    sysctls:
      - "net.ipv4.ping_group_range=0 2147483647"
    command: ["sleep", "inf"]
