version: '3.7'

services:
  route:
    image: wpengine/iptables@sha256:83833e038941488b8e7b02d961d42966093f9de1c336d84e541c0fb6589eaf7c
    restart: unless-stopped
    init: true
    stop_signal: SIGKILL
    volumes:
      - "./wireguardserver/config:/etc/wireguard:ro"
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv4.ping_group_range=0 2147483647"
      - "net.ipv4.ip_forward=1"
    command: ["sh", "-c", "iptables -t nat -A POSTROUTING -j MASQUERADE &&
                           iptables -A FORWARD -s $(cat /etc/wireguard/address) \
                                               -d $(cat /etc/wireguard/address) -j REJECT &&
                           iptables -A FORWARD -j ACCEPT &&
                           iptables -t mangle -A FORWARD -j TTL --ttl-inc 1 &&
                           exec tail -f /dev/null"]
  wireguardserver:
    build: build/wireguardserver
    restart: unless-stopped
    volumes:
      - "./wireguardserver/config:/etc/wireguard:ro"
      - "./wireguardserver/scripts:/opt/scripts:ro"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    pid: "service:route"
    ports:
      - 51820:51820/udp
    command: ["/opt/scripts/wgserver-run.sh"]
