version: '3.7'

services:
  openvpn:
    image: lawtancool/docker-openvpn-xor@sha256:5c4169cb95e63b73c661c5e31dd7e85e55a7083f246953011864e817f3481846
    restart: unless-stopped
    volumes:
      - "./resolv.conf:/etc/netns/route/resolv.conf"
      - "./vpn:/etc/openvpn:ro"
      - "./scripts:/opt/scripts:ro"
      - "./rr:/var/rr:rw"
    pid: "service:route"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    command: ["/opt/scripts/ovpn-run.sh", "--up-restart"]
  route:
    image: busybox
    restart: unless-stopped
    init: true
    stop_signal: SIGKILL
    volumes:
      - "./resolv.conf:/etc/resolv.conf"
    network_mode: none
    sysctls:
      - "net.ipv4.ping_group_range=0 2147483647"
    command: ["sleep", "inf"]
  socks5:
    image: ghcr.io/wzshiming/socks5/socks5:v0.4.2@sha256:1aca1fa75fc2ebd0041ca6944627f48223541cf37e03722b2982e7f6c23af2c6
    restart: unless-stopped
    network_mode: "service:route"
    user: "17818"
  socat2unix:
    image: alpine/socat:1.7.4.4@sha256:93efcf633c5489b170404df25e289f811cabeea728a5367f0c9b1560982edf14
    restart: unless-stopped
    volumes:
      - "./sock:/var/sock:rw"
    network_mode: "service:route"
    command: ["unix-listen:/var/sock/socks5,fork,unlink-early", "tcp-connect:127.0.0.1:1080"]
  socat2port:
    image: alpine/socat:1.7.4.4@sha256:93efcf633c5489b170404df25e289f811cabeea728a5367f0c9b1560982edf14
    restart: unless-stopped
    volumes:
      - "./sock:/var/sock:ro"
    ports:
      - "1080:1080"
    command: ["tcp-listen:1080,fork", "unix-connect:/var/sock/socks5"]
