version: '3.7'

services:
  openvpn:
    image: lawtancool/docker-openvpn-xor@sha256:5c64db86390e61f767dc24b648fd58ec8574d3d9f477b278d4dc8bb3fa6cf90e
    restart: unless-stopped
    volumes:
      - "./resolv.conf:/etc/netns/route/resolv.conf"
      - "./vpn:/etc/openvpn:ro"
      - "./scripts:/opt/scripts:ro"
      - "./rr:/var/rr:rw"
    pid: "service:route"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    command: ["/opt/scripts/ovpn-run.sh", "--up-restart"]
  route:
    image: wpengine/iptables@sha256:83833e038941488b8e7b02d961d42966093f9de1c336d84e541c0fb6589eaf7c
    restart: unless-stopped
    init: true
    stop_signal: SIGKILL
    volumes:
      - "./resolv.conf:/etc/resolv.conf"
      - "./wireguardserver/config:/etc/wireguard:ro"
    cap_add:
      - NET_ADMIN
    networks:
      - bridge
    sysctls:
      - "net.ipv4.ping_group_range=0 2147483647"
      - "net.ipv4.ip_forward=1"
    command: ["sh", "-c", "iptables -t nat -A POSTROUTING -j MASQUERADE &&
                           iptables -A FORWARD -s $(cat /etc/wireguard/address) \
                                               -d $(cat /etc/wireguard/address) -j REJECT &&
                           iptables -A FORWARD -s $(cat /etc/wireguard/address) -o eth0 -j REJECT &&
                           iptables -A FORWARD -i eth0 -d $(cat /etc/wireguard/address) -j REJECT &&
                           iptables -A FORWARD -j ACCEPT &&
                           iptables -t mangle -A FORWARD -j TTL --ttl-inc 1 &&
                           ip route delete default && exec tail -f /dev/null"]
  wireguardserver:
    build: build/wireguardserver
    restart: unless-stopped
    volumes:
      - "./wireguardserver/config:/etc/wireguard:ro"
      - "./wireguardserver/scripts:/opt/scripts:ro"
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    pid: "service:route"
    ports:
      - 51820:51820/udp
    command: ["/opt/scripts/wgserver-run.sh"]
  dnsmasq:
    build: build/dnsmasq
    restart: unless-stopped
    stop_signal: SIGKILL
    network_mode: "service:route"
    command: --no-hosts --cache-size=0 --strict-order --clear-on-reload
networks:
  bridge:
    internal: false
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
